# Generated by Django 5.0 on 2023-12-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_client', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_fin',
            field=models.DateField(),
        ),
    ]
