# Generated by Django 5.0 on 2023-12-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_client', '0007_accesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
