# Generated by Django 5.0 on 2024-01-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_client', '0008_alter_accesstoken_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessToken',
        ),
    ]
