# Generated by Django 5.0 on 2024-01-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_client', '0010_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='token',
            field=models.TextField(unique=True),
        ),
    ]
